#!/usr/bin/env sh
set -eu

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

python3 scripts/sync_queries.py

git add -- \
  expr/queries \
  core/queries \
  udl/queries \
  objectscript/queries \
  objectscript_routine/queries \
  bindings/python/tree_sitter_objectscript/queries \
  bindings/python/tree_sitter_objectscript_core/queries \
  bindings/python/tree_sitter_objectscript_udl/queries \
  bindings/python/tree_sitter_objectscript_expr/queries \
  bindings/python/tree_sitter_objectscript_routine/queries

npm run lint -- --fix
npm run lint
git add -- \
  common/define_grammar.js \
  common/keywords.js \
  objectscript/grammar.js \
  udl/grammar.js \
  core/grammar.js \
  expr/grammar.js \
  objectscript_routine/grammar.js

for grammar in objectscript udl core expr objectscript_routine; do
  (
    cd "$grammar"
    tree-sitter test
  )
done

make formatquery
git add -- \
  expr/queries \
  core/queries \
  udl/queries \
  objectscript/queries \
  objectscript_routine/queries \
  bindings/python/tree_sitter_objectscript/queries \
  bindings/python/tree_sitter_objectscript_core/queries \
  bindings/python/tree_sitter_objectscript_udl/queries \
  bindings/python/tree_sitter_objectscript_expr/queries \
  bindings/python/tree_sitter_objectscript_routine/queries

make lintquery
make checkquery
