[package]
name = "tree-sitter-objectscript"
description = "ObjectScript UDL grammar for tree-sitter"
version = "1.9.3"
keywords = ["incremental", "parsing", "objectscript", "udl"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
edition = "2021"
license = "MIT"
authors = [
  "Dave McCaldon <davem@intersystems.com>",
  "Hannah Kimura <hkimura@intersystems.com>",
]
build = "bindings/rust/build.rs"
include = [
  "/LICENSE",
  "/cargo_readme.md",
  "/bindings/rust/build.rs",
  "/bindings/rust/lib.rs",
  "/common/scanner.h",
  "/udl/src/parser.c",
  "/udl/src/scanner.c",
  "/udl/src/node-types.json",
  "/udl/src/tree_sitter/parser.h",
  "/udl/queries/highlights.scm",
  "/udl/queries/indents.scm",
  "/udl/queries/injections.scm",
  "/udl/queries/studio-highlights.scm",
]
readme = "cargo_readme.md"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = ">=0.26.6"
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0"
