[package]
name = "tree-sitter-objectscript"
description = "ObjectScript grammars for tree-sitter"
version = "1.3.4"
keywords = ["incremental", "parsing", "objectscript"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
edition = "2021"
license = "MIT"
authors = [
  "Dave McCaldon <davem@intersystems.com>",
  "Hannah Kimura <hkimura@intersystems.com>",
]
build = "bindings/rust/build.rs"
include = [
  "LICENSE", "bindings/rust", "core/src",
  "udl/src", "expr/src", "udl/queries/*", "core/queries/*",
  "common", "expr/queries/*", "udl/grammar.js", "core/grammar.js","expr/grammar.js","./tree-sitter.json"
]
readme = "cargo_readme.md"

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = ">=0.22.6"
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0"
