[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tree-sitter-objectscript"
description = "Objectscript grammar for tree-sitter"
version = "1.9.8"
keywords = ["incremental", "parsing", "tree-sitter", "objectscript"]
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed"
]
authors = [
  { name = "Dave McCaldon", email = "davem@intersystems.com" },
  { name = "Hannah Kimura", email = "hkimura@intersystems.com" },
]
requires-python = ">=3.9"
license.text = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://github.com/intersystems/tree-sitter-objectscript"

[project.optional-dependencies]
core = ["tree-sitter~=0.23"]

[tool.cibuildwheel]
build = "cp39-*"
build-frontend = "build"
