ROUTINE test 
cond(log,view=0,sqline) ; //DPV1693 (added view,sqline parameters)
	#; $$:  Return the Expression of the log# - without the IF.
	#;  Unless atomic, the returned expression must be in Parenthesis.
	#;  This is very recursive - so watch out!
	#;------------------------------------------------------------
	n buf,%classname,cond,funcsrc,i,%methodname,%mmm0co,mod,op,opflag,oper,string,%symtab,val4  //DPV1693, not new davals	// DPV3337 (%classname,%methodname,%symtax - used in LINES^%qarmac)
	s opflag=0,mod=0  ; set up stuff used in ptvalue^%qaqcpr

#IF 0	; JLF158+
	i $e(string)="l" {
	        s op=$p(string,"^",2),val4=$$cond($p(string,"^",4),-1)
#ELSE ;op	; JLF158=
	s op=$p($p(string,"^",2),"%NOINDEX") // PVA242
	#;  Generate the BuildValueArray loop for %ANYOF conditions
	#;
	n aoi,baseFld s baseFld=""
	#; f aoi=$ll($g($$$mtAnyOfVals(log))):-1:1 { if '$d(mt("anyofInProgress",$li($$$mtAnyOfVals(log),aoi))) { s baseFld=$li($$$mtAnyOfVals(log),aoi) quit }}
	if (baseFld="") && (op="ANYOFAND") 
	{	s op = "&&" }		// if not marked in mt("anyof",log), then just process it like a wide AND
	elseif (baseFld'="")
	{	 }
        SET string1="123 Primrose Path"
 SET len=$LENGTH(string1)
 FOR index=1:1:len-1 {
	        
  #ENDIF			// DPV2947
	WRITE $EXTRACT(string1,index)
        }


