/* eslint-disable indent */

/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

const STATEMENT_RULE_NAMES = [
  'print_statement',
  'command_set',
  'command_write',
  'command_do',
  'command_zwrite',
  'command_for',
  'command_while',
  'command_kill',
  'command_lock',
  'command_read',
  'command_open',
  'command_close',
  'command_use',
  'command_new',
  'command_if',
  'command_else',
  'command_throw',
  'command_trycatch',
  'command_job',
  'command_break',
  'command_merge',
  'command_quit',
  'command_goto',
  'command_return',
  'command_halt_or_hang',
  'command_dowhile',
  'command_continue',
  'command_tcommit',
  'command_trollback',
  'command_tstart',
  'command_view',
  'command_xecute',
  'command_zbreak',
  'command_zkill',
  'command_zn',
  'command_zsu',
  'command_ztrap',
  'command_zz',
  'commands_with_printlist',
  'objectscript_built_in_command',
  'embedded_html',
  'embedded_xml',
  'embedded_sql',
  'embedded_js',
  'pound_dim',
  'pound_define',
  'pound_def1arg',
  'pound_if',
  'pound_ifdef',
  'pound_ifndef',
  'pound_import',
  'pound_include',
  'command_macro',
  'tag',
  'tag_with_params',
  'procedure',
];

const OBJECTSCRIPT_BUILT_IN_COMMAND_PATTERNS = [
  /mv/i,
  /MVDIM/i,
  /Za(llocate)?/i,
  /zd(eallocate)?/i,
  /zdelete/i,
  /zerase/i,
  /zetrap/i,
  /zfile/i,
  /zhtrap/i,
  /zi(nsert)?/i,
  /zitrap/i,
  /zl(oad)?/i,
  /zns/i,
  /zg(o)/i,
  /zmove/i,
  /ZOMSPACK/i,
  /ZONERROR/i,
  /ZOS/i,
  /ZREAD/i,
  /ZS(AVE)?/i,
  /ZSYNC/i,
  /ZTA/i,
  /ZTb/i,
  /ZTe/i,
  /ZTRANSACTION/i,
  /zu(se)?/i,
];

const PRINTLIST_COMMAND_PATTERNS = [
  /MVC(RT)?/i,
  /MV(PRINT)?/i,
];

module.exports = {
  STATEMENT_RULE_NAMES,
  OBJECTSCRIPT_BUILT_IN_COMMAND_PATTERNS,
  PRINTLIST_COMMAND_PATTERNS,
};
