; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files (core/queries, udl/queries).
; File: indents.scm
; === BEGIN EXPR ===
; === END EXPR ===
; === BEGIN LOCAL ===
"{" @indent.begin

"}" @indent.end

; === END LOCAL ===
