; AUTO-GENERATED by scripts/sync_queries.py
; Edit only the LOCAL section in composed files.
; File: studio-highlights.scm
; === BEGIN LOCAL ===
(iris_username) @variable.member

[
  (keyword_import)
  (keyword_include)
  (keyword_includegenerator)
  (keyword_class)
  (keyword_method)
  (keyword_classmethod)
  (class_extends)
  (keyword_xdata)
  (keyword_query)
  (keyword_foreignkey)
  (keyword_index)
  (keyword_property)
  (keyword_projection)
  (keyword_relationship)
  (keyword_parameter)
  (keyword_references)
  (keyword_trigger)
  (keyword_storage)
] @keyword.type

(class_definition
  (class_name) @keyword.type
)

;start brackets representing keywords 
;@punctuation.special -> black fg, default bg
(query_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(class_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(query_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(property_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(parameter_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(method_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(foreignkey_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(index_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(extent_index_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(call_method_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(projection_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(relationship_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(expression_method_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(external_method_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(xdata_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(storage_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)

(trigger_keywords 
  [
    "["
    "]"
  ] @punctuation.special
)
; end brackets representing keywords

(class_keyword
  (_
    [
      "{"
      "}"
    ] @punctuation.special
  )
)

(class_keyword_owner 
[
  "{"
  "}"
] @punctuation.special
)

(documatic_line) @comment.documentation @spell

; start keywords
; @keyword.operator -> navy fg, default bg
; 

[
(xdata_keyword)
(class_keyword) 
(method_keyword)
(expression_method_keywords)
(call_method_keywords)
(external_method_keywords)
(foreignkey_keyword)
(index_keyword)
(index_keyword_extent)
(keyword_byref)
(keyword_output)
(parameter_keyword)
(property_keyword)
(projection_keyword)
(relationship_keyword)
(query_keyword)
(trigger_keyword)
]@keyword.operator

(property_keyword 
	(_ (query_name) @variable.member.sql)
)

(query_keyword 
	(_ (query_name) @variable.member.sql)
)

(class_keyword 
	(_ (query_name) @variable.member.sql)
)

(index_keyword 
	(_ (query_name) @variable.member.sql)
)

(method_keyword 
	(_ (query_name) @variable.member.sql)
)

(trigger_keyword 
	(_ (query_name) @variable.member.sql)
)

(class_keyword 
	(_ 
  [
    (property_name)
    (typename)
    (storage_name)
  ]@type.definition
  )
)

(query_keyword 
	(_ 
  [
    (property_name)
    (typename)
  ]@type.definition
  )
)

(relationship_keyword 
	(_ 
  [
    (variable_datatype)
    (typename)
  ]@type.definition
  )
)

(method_keyword 
	(_ 
  [
    (property_name)
    (typename)
    (xml_identifier)
  ]@type.definition
  )
)

(method_keyword_external_proc_name
(objectscript_identifier) @type.definition
)

(parameter_keyword 
	(_ 
  [
    (typename)
    (keyword_list)
  ]@type.definition
  )
)

(trigger_keyword 
	(_ 
  [
    (typename)
    (trigger_event_value)
  ]@type.definition
  )
)

(property_keyword 
	(_ 
  [
    (typename)
  ]@type.definition
  )
)

(property_keyword_aliases (property_name) @variable.member)

(foreignkey_keyword 
(_
(typename) @type.definition
))

(foreignkey_keyword 
	(_ (query_name) @variable.member.sql)
)

(expression_method_keywords 
(_
(typename) @type.definition
))

(call_method_keywords 
(_
(typename) @type.definition
))

(external_method_keywords 
(_
(typename) @type.definition
))

(method_keyword 
(_
(method_name) @variable.member
))

; start class member names 
; @variable.member -> black fg, default bg
(method_definition (method_name) @variable.member)
(xdata (xdata_name) @variable.member)
(property (property_name) @variable.member)
(parameter (parameter_name) @variable.member)
(relationship (relationship_name) @variable.member)
(query (query_name) @variable.member)
(foreignkey
[
  (foreignkey_name)
  (property_name)
  (index_name)
] @variable.member
)
(index
(index_name) @variable.member
)

(projection
(projection_name) @variable.member
)

(trigger (trigger_name) @variable.member)

(storage (storage_name) @variable.member)
; end class member names 

(foreignkey (class_name) @keyword.type)

(xdata_keyword 
(_
(typename) @type.definition
))

(xdata_keyword_mimetype (typename) @type.definition) @keyword.operator

; start return_type @keyword.type
(return_type) @keyword.type
; end return_type

; start method_arg @variable.parameter
(method_arg) @variable.parameter
(method_arg (lvn (objectscript_identifier) @variable.parameter))
(method_arg (expr_atom (lvn (objectscript_identifier) @variable.parameter)))
; end method_arg @variable.parameter

; === END LOCAL ===
