#!/usr/bin/env python3
"""Synchronize layered query files and Python binding query copies.

Composition rules use ONLY each file's LOCAL block content.

Append matrix:
- expr: nothing appended
- core:
  - highlights.scm: expr
  - indents.scm: nothing
  - injections.scm: nothing
- udl:
  - highlights.scm: expr + core
  - indents.scm: core
  - injections.scm: core
- objectscript:
  - highlights.scm: expr + core + udl
  - indents.scm: core
  - injections.scm: core + udl
- objectscript_routine:
  - highlights.scm: expr + core
  - indents.scm: core
  - injections.scm: core

Python bindings are copied from composed query trees:
- bindings/python/tree_sitter_objectscript/queries <- objectscript/queries
- bindings/python/tree_sitter_objectscript_core/queries <- core/queries
- bindings/python/tree_sitter_objectscript_udl/queries <- udl/queries
- bindings/python/tree_sitter_objectscript_expr/queries <- expr/queries
- bindings/python/tree_sitter_objectscript_routine/queries <- objectscript_routine/queries
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

EXPR_DIR = ROOT / "expr" / "queries"
CORE_DIR = ROOT / "core" / "queries"
UDL_DIR = ROOT / "udl" / "queries"
OBJECTSCRIPT_DIR = ROOT / "objectscript" / "queries"
ROUTINE_DIR = ROOT / "objectscript_routine" / "queries"

QUERY_FILENAMES = ("highlights.scm", "indents.scm", "injections.scm")
IGNORED_QUERY_FILENAMES = {"studio-highlights.scm"}

GRAMMAR_DIRS: dict[str, Path] = {
    "expr": EXPR_DIR,
    "core": CORE_DIR,
    "udl": UDL_DIR,
    "objectscript": OBJECTSCRIPT_DIR,
    "objectscript_routine": ROUTINE_DIR,
}

APPEND_SOURCES: dict[str, dict[str, list[str]]] = {
    "core": {
        "highlights.scm": ["expr"],
        "indents.scm": [],
        "injections.scm": [],
    },
    "udl": {
        "highlights.scm": ["expr", "core"],
        "indents.scm": ["core"],
        "injections.scm": ["core"],
    },
    "objectscript": {
        "highlights.scm": ["expr", "core", "udl"],
        "indents.scm": ["core"],
        "injections.scm": ["core", "udl"],
    },
    "objectscript_routine": {
        "highlights.scm": ["expr", "core"],
        "indents.scm": ["core"],
        "injections.scm": ["core"],
    },
}

LOCAL_BEGIN_MARKERS = {"; === BEGIN LOCAL ===", "; BEGIN LOCAL"}
LOCAL_END_MARKERS = {"; === END LOCAL ===", "; END LOCAL"}

PYTHON_QUERY_DIRS: tuple[tuple[Path, Path], ...] = (
    (OBJECTSCRIPT_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript" / "queries"),
    (CORE_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_core" / "queries"),
    (UDL_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_udl" / "queries"),
    (EXPR_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_expr" / "queries"),
    (ROUTINE_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_routine" / "queries"),
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def strip_inherits_header(content: str) -> str:
    lines = content.splitlines()
    if lines and re.match(r"^\s*;\s*inherits:\s*", lines[0]):
        lines = lines[1:]
    while lines and lines[0].strip() == "":
        lines = lines[1:]
    while lines and lines[-1].strip() == "":
        lines = lines[:-1]
    return "\n".join(lines)


def extract_local_layer(content: str) -> str:
    if not content:
        return ""

    lines = content.splitlines()
    begin = None
    end = None

    for i, line in enumerate(lines):
        if line.strip() in LOCAL_BEGIN_MARKERS:
            begin = i
            break

    if begin is not None:
        for i in range(begin + 1, len(lines)):
            if lines[i].strip() in LOCAL_END_MARKERS:
                end = i
                break

    if begin is None or end is None:
        return strip_inherits_header(content)

    local = "\n".join(lines[begin + 1 : end])
    return local.strip("\n")


def render_composed_file(filename: str, sections: list[tuple[str, str]]) -> str:
    output: list[str] = [
        "; AUTO-GENERATED by scripts/sync_queries.py",
        "; Edit only the LOCAL section in composed files.",
        f"; File: {filename}",
    ]

    for label, body in sections:
        output.append(f"; === BEGIN {label} ===")
        if body:
            output.append(body.rstrip("\n"))
            output.append("")
        output.append(f"; === END {label} ===")

    return "\n".join(output).rstrip() + "\n"


def list_query_files() -> list[str]:
    names: set[str] = set(QUERY_FILENAMES)
    for directory in GRAMMAR_DIRS.values():
        if directory.exists():
            names.update(
                p.name
                for p in directory.glob("*.scm")
                if p.name not in IGNORED_QUERY_FILENAMES
            )
    return sorted(names)


def sync_python_query_dir(src_dir: Path, dst_dir: Path) -> None:
    dst_dir.mkdir(parents=True, exist_ok=True)

    src_files = {
        p.name: p for p in src_dir.glob("*.scm") if p.name not in IGNORED_QUERY_FILENAMES
    }
    dst_files = {
        p.name: p for p in dst_dir.glob("*.scm") if p.name not in IGNORED_QUERY_FILENAMES
    }

    for stale_name in sorted(set(dst_files) - set(src_files)):
        dst_files[stale_name].unlink()

    for name, src_path in sorted(src_files.items()):
        shutil.copyfile(src_path, dst_dir / name)


def read_query_files(path: Path) -> dict[str, str]:
    return {
        p.name: read_text(p)
        for p in sorted(path.glob("*.scm"))
        if p.name not in IGNORED_QUERY_FILENAMES
    }


def check_python_query_dirs() -> list[str]:
    mismatches: list[str] = []
    for src_dir, dst_dir in PYTHON_QUERY_DIRS:
        src_files = read_query_files(src_dir)
        dst_files = read_query_files(dst_dir)
        src_names = set(src_files)
        dst_names = set(dst_files)

        missing = sorted(src_names - dst_names)
        extra = sorted(dst_names - src_names)
        different = sorted(
            name for name in (src_names & dst_names) if src_files[name] != dst_files[name]
        )

        if not missing and not extra and not different:
            continue

        mismatches.append(f"{dst_dir.relative_to(ROOT)} != {src_dir.relative_to(ROOT)}")
        for name in missing:
            mismatches.append(f"  missing in destination: {name}")
        for name in extra:
            mismatches.append(f"  extra in destination: {name}")
        for name in different:
            mismatches.append(f"  content differs: {name}")

    return mismatches


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-python",
        action="store_true",
        help="Verify Python query directories match their source query directories.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.check_python:
        mismatches = check_python_query_dirs()
        if mismatches:
            print("Python query copies are out of sync:", file=sys.stderr)
            print("\n".join(mismatches), file=sys.stderr)
            print("\nRun: python3 scripts/sync_queries.py", file=sys.stderr)
            raise SystemExit(1)
        return

    filenames = list_query_files()

    local_layers: dict[str, dict[str, str]] = {
        grammar: {
            name: extract_local_layer(read_text(directory / name))
            for name in filenames
        }
        for grammar, directory in GRAMMAR_DIRS.items()
    }

    for grammar, append_map in APPEND_SOURCES.items():
        target_dir = GRAMMAR_DIRS[grammar]
        for name in filenames:
            append_sources = append_map.get(name, [])
            sections: list[tuple[str, str]] = []

            for source in append_sources:
                sections.append((source.upper(), local_layers[source][name]))

            sections.append(("LOCAL", local_layers[grammar][name]))

            # Avoid creating arbitrary new files outside the canonical query set.
            if name not in QUERY_FILENAMES and not any(body for _, body in sections):
                continue

            write_text(target_dir / name, render_composed_file(name, sections))

    for src_dir, dst_dir in PYTHON_QUERY_DIRS:
        sync_python_query_dir(src_dir, dst_dir)


if __name__ == "__main__":
    main()
