#!/usr/bin/env python3
"""Synchronize layered query files and Python binding query copies.

Composition rules:
- expr/queries: keep as-is (source of expr layer)
- core/queries: expr layer + core local layer
- udl/queries: expr layer + core local layer + udl local layer

Python bindings are copied from the composed trees:
- bindings/python/tree_sitter_objectscript/queries <- udl/queries
- bindings/python/tree_sitter_objectscript_core/queries <- core/queries
- bindings/python/tree_sitter_objectscript_udl/queries <- udl/queries
- bindings/python/tree_sitter_objectscript_expr/queries <- expr/queries
"""

from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

EXPR_DIR = ROOT / "expr" / "queries"
CORE_DIR = ROOT / "core" / "queries"
UDL_DIR = ROOT / "udl" / "queries"

LOCAL_BEGIN = "; === BEGIN LOCAL ==="
LOCAL_END = "; === END LOCAL ==="

PYTHON_QUERY_DIRS: tuple[tuple[Path, Path], ...] = (
    (UDL_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript" / "queries"),
    (CORE_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_core" / "queries"),
    (UDL_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_udl" / "queries"),
    (EXPR_DIR, ROOT / "bindings" / "python" / "tree_sitter_objectscript_expr" / "queries"),
)


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8") if path.exists() else ""


def write_text(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def strip_inherits_header(content: str) -> str:
    lines = content.splitlines()
    if lines and re.match(r"^\s*;\s*inherits:\s*", lines[0]):
        lines = lines[1:]
    while lines and lines[0].strip() == "":
        lines = lines[1:]
    while lines and lines[-1].strip() == "":
        lines = lines[:-1]
    return "\n".join(lines)


def extract_local_layer(content: str) -> str:
    if not content:
        return ""

    lines = content.splitlines()
    try:
        begin = lines.index(LOCAL_BEGIN)
        end = lines.index(LOCAL_END, begin + 1)
    except ValueError:
        return strip_inherits_header(content)

    local = "\n".join(lines[begin + 1 : end])
    return local.strip("\n")


def render_composed_file(filename: str, sections: list[tuple[str, str]]) -> str:
    output: list[str] = [
        "; AUTO-GENERATED by scripts/sync_queries.py",
        "; Edit only the LOCAL section in composed files (core/queries, udl/queries).",
        f"; File: {filename}",
    ]

    for label, body in sections:
        output.append(f"; === BEGIN {label} ===")
        if body:
            output.append(body.rstrip("\n"))
            output.append("")
        output.append(f"; === END {label} ===")

    return "\n".join(output).rstrip() + "\n"


def list_query_files() -> list[str]:
    names: set[str] = set()
    for directory in (EXPR_DIR, CORE_DIR, UDL_DIR):
        if directory.exists():
            names.update(p.name for p in directory.glob("*.scm"))
    return sorted(names)


def sync_python_query_dir(src_dir: Path, dst_dir: Path) -> None:
    dst_dir.mkdir(parents=True, exist_ok=True)

    src_files = {p.name: p for p in src_dir.glob("*.scm")}
    dst_files = {p.name: p for p in dst_dir.glob("*.scm")}

    for stale_name in sorted(set(dst_files) - set(src_files)):
        dst_files[stale_name].unlink()

    for name, src_path in sorted(src_files.items()):
        shutil.copyfile(src_path, dst_dir / name)


def read_query_files(path: Path) -> dict[str, str]:
    return {p.name: read_text(p) for p in sorted(path.glob("*.scm"))}


def check_python_query_dirs() -> list[str]:
    mismatches: list[str] = []
    for src_dir, dst_dir in PYTHON_QUERY_DIRS:
        src_files = read_query_files(src_dir)
        dst_files = read_query_files(dst_dir)
        src_names = set(src_files)
        dst_names = set(dst_files)

        missing = sorted(src_names - dst_names)
        extra = sorted(dst_names - src_names)
        different = sorted(
            name for name in (src_names & dst_names) if src_files[name] != dst_files[name]
        )

        if not missing and not extra and not different:
            continue

        mismatches.append(f"{dst_dir.relative_to(ROOT)} != {src_dir.relative_to(ROOT)}")
        for name in missing:
            mismatches.append(f"  missing in destination: {name}")
        for name in extra:
            mismatches.append(f"  extra in destination: {name}")
        for name in different:
            mismatches.append(f"  content differs: {name}")

    return mismatches


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check-python",
        action="store_true",
        help="Verify Python query directories match their source query directories.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.check_python:
        mismatches = check_python_query_dirs()
        if mismatches:
            print("Python query copies are out of sync:", file=sys.stderr)
            print("\n".join(mismatches), file=sys.stderr)
            print("\nRun: python3 scripts/sync_queries.py", file=sys.stderr)
            raise SystemExit(1)
        return

    filenames = list_query_files()

    expr_raw = {name: strip_inherits_header(read_text(EXPR_DIR / name)) for name in filenames}
    core_local = {name: extract_local_layer(read_text(CORE_DIR / name)) for name in filenames}
    udl_local = {name: extract_local_layer(read_text(UDL_DIR / name)) for name in filenames}

    for name in filenames:
        expr_body = expr_raw[name]
        core_body = core_local[name]
        udl_body = udl_local[name]

        core_text = render_composed_file(
            name,
            [
                ("EXPR", expr_body),
                ("LOCAL", core_body),
            ],
        )

        udl_text = render_composed_file(
            name,
            [
                ("EXPR", expr_body),
                ("CORE", core_body),
                ("LOCAL", udl_body),
            ],
        )

        write_text(CORE_DIR / name, core_text)
        write_text(UDL_DIR / name, udl_text)

    for src_dir, dst_dir in PYTHON_QUERY_DIRS:
        sync_python_query_dir(src_dir, dst_dir)


if __name__ == "__main__":
    main()
