[package]
name = "tree-sitter-objectscript-routine"
description = "ObjectScript routine grammar for tree-sitter"
version = "1.8.6"
keywords = ["incremental", "parsing", "objectscript"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/intersystems/tree-sitter-objectscript"
edition = "2021"
license = "MIT"
authors = [
  "Dave McCaldon <davem@intersystems.com>",
  "Hannah Kimura <hkimura@intersystems.com>",
]
build = "build.rs"
include = [
  "/LICENSE",
  "/cargo_readme_routine.md",
  "/build.rs",
  "/lib.rs",
  "/common/scanner.h",
  "/objectscript_routine/src/parser.c",
  "/objectscript_routine/src/scanner.c",
  "/objectscript_routine/src/node-types.json",
  "/objectscript_routine/src/tree_sitter/parser.h",
  "/objectscript_routine/queries/highlights.scm",
  "/objectscript_routine/queries/indents.scm",
  "/objectscript_routine/queries/injections.scm",
  "/objectscript_routine/queries/studio-highlights.scm"
]
readme = "cargo_readme_routine.md"

[lib]
path = "lib.rs"

[dependencies]
tree-sitter = ">=0.26.6"
tree-sitter-language = "0.1"

[build-dependencies]
cc = "1.0"
