name: Publish packages

on:
  push:
    branches: [workflow_and_bindings]
    # tags: ["*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    if: github.repository == 'hkimura-intersys/tree-sitter-objectscript'
    uses: tree-sitter/workflows/.github/workflows/release.yml@main
    with:
      generate: true
  npm:
    uses: tree-sitter/workflows/.github/workflows/package-npm.yml@31a611b89757509757378e3d94f28a41a782d9df
    with:
      generate: true
    secrets:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@56557c4133653a3537051dbdc31f4af09dffaef4
    with:
      generate: true
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}

  crates:
    if: github.repository == 'hkimura-intersys/tree-sitter-objectscript'
    uses: tree-sitter/workflows/.github/workflows/package-crates.yml@main
    secrets:
      CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
    with:
      generate: true

  crates_playground:
    if: github.repository == 'hkimura-intersys/tree-sitter-objectscript'
    name: Publish Rust playground package
    runs-on: ubuntu-latest
    environment:
      name: crates
      url: https://crates.io/crates/tree-sitter-objectscript-playground
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Publish to crates.io
        run: ./scripts/rust_playground_crate.sh publish
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
